diff --git a/Makefile b/Makefile
index 598b363..a52d967 100644
--- a/Makefile
+++ b/Makefile
@@ -25,12 +25,12 @@ STATIC_LIBS   := \
 	$(LIBS_LOC)libstrop/bld/libstrop.a
 
 #--------------------- Cpp Lint -----------------------------------------------#
-LINT          := $(HOME)/.makeccpp/cpplint/cpplint.py
+LINT          := ../makeccpp/cpplint/cpplint.py
 LINT_FLAGS    :=
 
 #--------------------- Unit Tests ---------------------------------------------#
 TEST_SUFFIX   := _TEST
-GTEST_BASE    := $(HOME)/.makeccpp/gtest
+GTEST_BASE    := ../makeccpp/gtest
 
 #--------------------- Compilation and Linking --------------------------------#
 CXX           := g++
@@ -38,8 +38,8 @@ SRC_EXTS      := .cc
 HDR_EXTS      := .h .tcc
 CXX_FLAGS     := -Wall -Wextra -pedantic -Wfatal-errors -std=c++11
 CXX_FLAGS     += -Wno-unused-parameter -Wno-variadic-macros
-CXX_FLAGS     += -march=native -g -O3 -flto
+CXX_FLAGS     +=  -g -O3 -flto
 LINK_FLAGS    := -lz
 
 #--------------------- Auto Makefile ------------------------------------------#
-include $(HOME)/.makeccpp/auto_bin.mk
+include ../makeccpp/auto_bin.mk
